/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Auxiliares;

import com.mycompany.conexionbbdd.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC220
 */
public class Add_Pedido extends javax.swing.JPanel {

    /**
     * Creates new form Add_Pedido
     */
    
    private String fecha = ""; 
    private int id_pedido = 0; 
    private int id_cliente = 0; 
    
    PreparedStatement pt; 
    ResultSet rs; 
    String texto = "";
    
    public Add_Pedido() {
        initComponents();
        mostrarDatos(); 
    }
    
    public void mostrarDatos(){
        try { 
            pt = Conexion.getConnection().prepareStatement("SELECT * FROM pedido");
            rs = pt.executeQuery(); 
            
            while(rs.next()){
                fecha = rs.getString("fecha"); 
                id_pedido = rs.getInt("id_pedido"); 
                id_cliente = rs.getInt("id_cliente"); 
                
                String mensaje = "ID : " + this.id_pedido + " nombre : " + this.fecha + " ciudad: " + this.id_cliente  + "\n"; 
                
                texto = texto + mensaje; 
                
            }
            
            jTextArea1.setText(""); 
            jTextArea1.setText(texto);
            
        } catch (SQLException ex) {
            Logger.getLogger(Add_Pedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ID_Cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ID_Producto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        SendCliente = new javax.swing.JButton();

        jLabel1.setText("ID Cliente: ");

        jLabel2.setText("ID Producto:");

        jLabel3.setText("Cantidad :");

        jButton1.setText("Send");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        SendCliente.setText("Send");
        SendCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendClienteMouseClicked(evt);
            }
        });
        SendCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(ID_Cliente))
                    .addComponent(SendCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID_Producto)
                            .addComponent(Cantidad))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SendCliente)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try { 
            pt = Conexion.getConnection().prepareStatement("INSERT INTO pedido_producto(id_pedido, id_producto, cantidad) VALUES (?,?,?)");
            pt.setInt(1, Integer.parseInt(ID_Cliente.getText()));
            pt.setInt(2, Integer.parseInt(ID_Producto.getText()));
            pt.setInt(3, Integer.parseInt(Cantidad.getText()));
            pt.executeUpdate(); 
            
            int cantidad = 0; 
            pt = Conexion.getConnection().prepareStatement("SELECT * FROM producto WHERE id_producto = ?");
            pt.setInt(1, Integer.parseInt(ID_Producto.getText()));
            rs = pt.executeQuery(); 
            while(rs.next()){
                cantidad = rs.getInt("stock"); 
            }
            
            pt = Conexion.getConnection().prepareStatement("UPDATE producto SET stock = ? WHERE id_producto = ?"); 
            pt.setInt(1, cantidad - Integer.parseInt(Cantidad.getText()) );
            pt.setInt(2, Integer.parseInt(ID_Producto.getText())); 
            pt.executeUpdate(); 
            
            ID_Producto.setText("");
            Cantidad.setText(""); 
            
            mostrarDatos(); 
        } catch (SQLException ex) {
            Logger.getLogger(Add_Product.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void SendClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SendClienteMouseClicked

    private void SendClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendClienteActionPerformed
        try { 
            pt = Conexion.getConnection().prepareStatement("INSERT INTO pedido(fecha, id_cliente) VALUES (NOW(),?)");
            pt.setInt(1, Integer.parseInt(ID_Cliente.getText()));
            pt.executeUpdate(); 
            
            //ID_Cliente.setText(""); 
            mostrarDatos(); 
        } catch (SQLException ex) {
            Logger.getLogger(Add_Product.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            
        }
    }//GEN-LAST:event_SendClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField ID_Cliente;
    private javax.swing.JTextField ID_Producto;
    private javax.swing.JButton SendCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
