/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Auxiliares;

import com.mycompany.conexionbbdd.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC220
 */
public class ByID extends javax.swing.JPanel {

    /**
     * Creates new form ByID
     */
    
    PreparedStatement pt; 
    ResultSet rs; 
    int id_pedido = 0; 
    int cantidad =0; 
    int id_producto = 0; 
    String texto = ""; 
    
    private int id = 0; 
    
    public ByID() {
        initComponents();
    }

     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("ID Pedido: ");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(ID)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private String nombre, ciudad, fecha, nombre_producto; 
    private int cantidad_producto, precio, total; 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(!(ID.equals(""))){
                pt = Conexion.getConnection().prepareStatement("SELECT \n" +
                                        "	c.nombre AS Nombre,\n" +
                                        "    c.ciudad AS Ciudad, \n" +
                                        "    p.fecha AS Fecha, \n" +
                                        "    pr.nombre AS Nombre_Producto, \n" +
                                        "    pp.cantidad AS Cantidad,\n" +
                                        "    pr.precio AS Precio, \n" +
                                        "    SUM(pr.precio * pp.cantidad) AS Total \n" +
                                        "FROM pedido p \n" +
                                        "	JOIN cliente c ON p.id_cliente = c.id_cliente\n" +
                                        "    JOIN pedido_producto pp ON p.id_pedido = pp.id_pedido\n" +
                                        "    JOIN producto pr ON pr.id_producto = pp.id_producto\n" +
                                        "WHERE p.id_pedido = ?\n" +
                                        "GROUP BY c.nombre, c.ciudad, p.fecha, pr.nombre,pp.cantidad, pr.precio;");
                pt.setInt(1, Integer.parseInt(ID.getText()));
                rs = pt.executeQuery(); 
                
                while(rs.next()){
                    cantidad_producto = rs.getInt("Cantidad"); 
                    precio = rs.getInt("Precio"); 
                    total = rs.getInt("Total"); 
                    nombre = rs.getString("Nombre"); 
                    ciudad = rs.getString("Ciudad"); 
                    fecha = rs.getString("Fecha"); 
                    nombre_producto = rs.getString("Nombre_Producto"); 


                    String mensaje = "Nombre : " + this.nombre + " Ciudad : " 
                            + this.ciudad+ " Fecha : "+ this.fecha + " Nombre del Producto : "+ this.nombre_producto
                            + " Cantidad: " + this.cantidad 
                            + " Precio : " + this.precio 
                            + " Total : " + this.total+  "\n"; 

                    texto = texto + mensaje; 
                
                }

                jTextArea1.setText(""); 
                jTextArea1.setText(texto);

            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
