/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.conexionbbdd;

import Auxiliares.Add_Pedido;
import Auxiliares.Add_Product;
import Auxiliares.Add_cliente;
import Auxiliares.ByID;
import Auxiliares.Delete;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author PC220
 */
public class Interfaz extends javax.swing.JFrame {

    private CardLayout cardLayout; 
    
    /**
     * Creates new form UltimoEjercicioPreEvaluable
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarCardLayout(); 
        
        setFocusable(true); 
    }

    Random r =new Random(); 
    
    private void configurarCardLayout(){
        cardLayout = (CardLayout) Panel2.getLayout(); 
        
        Panel2.add(new Add_Product(), "Producto"); 
        Panel2.add(new Add_cliente(), "Cliente");
        Panel2.add(new Add_Pedido(), "Pedido");
        Panel2.add(new ByID(), "ByID"); 
        Panel2.add(new Delete(), "Delete"); 
        /*
        Panel2.add(new PanelHora(), "Hora"); 
        Panel2.add(new PanelWindows(), "Windows"); 
        */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Panel1 = new javax.swing.JPanel();
        Inicio = new javax.swing.JButton();
        Sistema = new javax.swing.JButton();
        Windows1 = new javax.swing.JButton();
        Hora = new javax.swing.JButton();
        Windows = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IP = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Panel1.setLayout(new java.awt.GridLayout(8, 1));

        Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Inicio.setForeground(new java.awt.Color(0, 0, 0));
        Inicio.setText("Añadir Producto");
        Inicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Inicio.setFocusable(false);
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });
        Inicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InicioKeyPressed(evt);
            }
        });
        Panel1.add(Inicio);

        Sistema.setBackground(new java.awt.Color(255, 255, 255));
        Sistema.setForeground(new java.awt.Color(0, 0, 0));
        Sistema.setText("Añadir Cliente");
        Sistema.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Sistema.setFocusable(false);
        Sistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SistemaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SistemaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SistemaMouseExited(evt);
            }
        });
        Sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SistemaActionPerformed(evt);
            }
        });
        Sistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SistemaKeyPressed(evt);
            }
        });
        Panel1.add(Sistema);

        Windows1.setBackground(new java.awt.Color(255, 255, 255));
        Windows1.setForeground(new java.awt.Color(0, 0, 0));
        Windows1.setText("Añadir Pedido");
        Windows1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Windows1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Windows1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Windows1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Windows1MouseExited(evt);
            }
        });
        Windows1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Windows1ActionPerformed(evt);
            }
        });
        Panel1.add(Windows1);

        Hora.setBackground(new java.awt.Color(255, 255, 255));
        Hora.setForeground(new java.awt.Color(0, 0, 0));
        Hora.setText("Buscar Pedido por ID");
        Hora.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Hora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoraMouseExited(evt);
            }
        });
        Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraActionPerformed(evt);
            }
        });
        Hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HoraKeyPressed(evt);
            }
        });
        Panel1.add(Hora);

        Windows.setBackground(new java.awt.Color(255, 255, 255));
        Windows.setForeground(new java.awt.Color(0, 0, 0));
        Windows.setText("Borrar Pedido");
        Windows.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Windows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WindowsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WindowsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WindowsMouseExited(evt);
            }
        });
        Panel1.add(Windows);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(Panel1, gridBagConstraints);

        Panel2.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Inicio");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("IP : ");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Pass : ");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(IP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        Panel2.add(jPanel2, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(Panel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseEntered
        
    }//GEN-LAST:event_InicioMouseEntered

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseExited

    }//GEN-LAST:event_InicioMouseExited

    private void SistemaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SistemaMouseEntered

    }//GEN-LAST:event_SistemaMouseEntered

    private void SistemaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SistemaMouseExited

    }//GEN-LAST:event_SistemaMouseExited

    private void HoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraMouseEntered

    }//GEN-LAST:event_HoraMouseEntered

    private void HoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraMouseExited

    }//GEN-LAST:event_HoraMouseExited

    private void WindowsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WindowsMouseEntered

    }//GEN-LAST:event_WindowsMouseEntered

    private void WindowsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WindowsMouseExited
    }//GEN-LAST:event_WindowsMouseExited

    // Para cambiar a la ventana de inicio.
    
    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked

        cardLayout.show(Panel2, "Producto");
        
        
    }//GEN-LAST:event_InicioMouseClicked

    private void SistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SistemaMouseClicked
        cardLayout.show(Panel2, "Cliente");
    }//GEN-LAST:event_SistemaMouseClicked

    private void HoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraMouseClicked
       
    }//GEN-LAST:event_HoraMouseClicked

    private void WindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WindowsMouseClicked
        cardLayout.show(Panel2, "Delete");
    }//GEN-LAST:event_WindowsMouseClicked

    
    
    private void InicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InicioKeyPressed
        
        cardLayout.show(Panel2, "Inicio");
    }//GEN-LAST:event_InicioKeyPressed

    private void SistemaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SistemaKeyPressed
        cardLayout.show(Panel2, "Sistema");
    }//GEN-LAST:event_SistemaKeyPressed

    private void HoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HoraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraKeyPressed

    
    
    
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int code = evt.getKeyCode(); 
        
        if(code == KeyEvent.VK_Q){
            cardLayout.show(Panel2, "Producto");

        }else if(code == KeyEvent.VK_W){
            cardLayout.show(Panel2, "Cliente");
        }else if(code == KeyEvent.VK_E){
            cardLayout.show(Panel2, "Pedido"); 
        }else if(code == KeyEvent.VK_R){
            cardLayout.show(Panel2, "ByID"); 
        }else if(code == KeyEvent.VK_T){
            cardLayout.show(Panel2, "Delete");
        }
        
        requestFocusInWindow(); 

    }//GEN-LAST:event_formKeyPressed

    private void Windows1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Windows1MouseClicked
       cardLayout.show(Panel2, "Pedido");
    }//GEN-LAST:event_Windows1MouseClicked

    private void Windows1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Windows1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Windows1MouseEntered

    private void Windows1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Windows1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Windows1MouseExited

    private void Windows1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Windows1ActionPerformed
       cardLayout.show(Panel2, "Pedido");
    }//GEN-LAST:event_Windows1ActionPerformed

    private void SistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SistemaActionPerformed

    private void HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraActionPerformed
        cardLayout.show(Panel2, "ByID");
    }//GEN-LAST:event_HoraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Conexion.ip = IP.getText(); 
        Conexion.user = Usuario.getText(); 
        Conexion.pass = Pass.getText(); 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hora;
    private javax.swing.JTextField IP;
    private javax.swing.JButton Inicio;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JTextField Pass;
    private javax.swing.JButton Sistema;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton Windows;
    private javax.swing.JButton Windows1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
